In [1]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [2]:
cal = A.sum(axis=0) # this means to sum vertically
print(cal)

[ 59.  239.  155.4  76.9]


In [3]:
percentage = 100*A/cal.reshape(1,4) #example of python broadcasting
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


## A note on python/numpy vectors


In [4]:
import numpy as np

a = np.random.randn(5) #dont use this formatdfsz\43  

In [5]:
print(a)

[-0.57018802 -0.92831469 -0.19266028 -2.42619792 -0.22933889]


In [6]:
print(a.shape)

(5,)


In [8]:
print(a.T)
print(np.dot(a,a.T))

[-0.57018802 -0.92831469 -0.19266028 -2.42619792 -0.22933889]
7.163033220635394


In [9]:
a= np.random.randn(5,1)
print(a)

[[ 0.88943394]
 [ 0.69812608]
 [ 0.31751429]
 [-0.77464661]
 [ 0.44453987]]


In [10]:
print(a.T)

[[ 0.88943394  0.69812608  0.31751429 -0.77464661  0.44453987]]
